### ISSUE TITLE
Gradient is not stable

### ISSUE THREAD

**Issue by ersanliqiao** [generalized-iou/g-darknet#10]
The train loss suddenly become big and loss become NAN, how should I overcome this?

**Comment by sbastani** [comment]
@ersanliqiao I have the same problem. Did you manage to solve the issue?

**Comment by ersanliqiao** [comment]
@sbastani No, I have try to not update weights when it's loss is Nan, but does not work!

**Comment by nathantsoi** [comment]
Do your learning rate and burn in configuration options match your GPU count? Also, make sure you train the first ~1k iterations on a single GPU.
