### ISSUE TITLE
About the results of VOC in readme

### ISSUE THREAD

**Issue by 1005673201** [generalized-iou/g-darknet#11]
Your VOC GIoU result was trained by using  cfg/runs/yolov3-giou-40/yolov3-voc.yolov3-giou-40.cfg. However, this cfg is set to 416, and your paper said you used darknet608 in all experiments. Right?

**Comment by nathantsoi** [comment]
You are correct. We keep the default configurations from the original darknet code for each dataset. (e.g. [608 for coco](https://github.com/pjreddie/darknet/blob/master/cfg/yolov3.cfg) and [416 for voc](https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-voc.cfg))

**Comment by 1005673201** [comment]
Hi，I'm also curious in section 3 in your paper recently. How to prove the triangle inequality for L_GIoU? After my simple attempt, I found that it seems to be not easy. Is the proof simple? Within or beyond one page? If you don't mind, may I have a look at the supp. material to your paper?




------------------ 原始邮件 ------------------
发件人: "Nathan"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 凌晨1:27
收件人: "generalized-iou/g-darknet"<g-darknet@noreply.github.com>;
抄送: "曲終人不散丶"<1005673201@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [generalized-iou/g-darknet] About the results of VOC in readme(#11)




You are correct. We keep the default configurations from the original darknet code for each dataset. (e.g. 608 for coco and 416 for voc)
