### ISSUE TITLE
compile questions

### ISSUE THREAD

**Issue by 1215907651** [generalized-iou/g-darknet#3]
Dear professor
I am a scholar and I am working on the same direction of detection as yours. First of all, congratulations on your outstanding masterpiece on CVPR2019. For the source code g-datknet-master you open on github, I would like to ask you some question. I already have a trainable original YOLOV3 darknet that has been compiled successfully on win10. I don't know how to compile the code g-darknet-master you posted on github? If you can take the time to tell me in your busy schedule, I will be very grateful.

**Comment by 1215907651** [comment]
Dear professor,
when i compiled the g-darknet, there were some errors like these:
/usr/local/include/opencv2/core/cvdef.h:485:1 error: unkown type name 'namespace'
namespace cv{....

version:
cuda: 10.0
opencv: 3.4
gcc: 5.4.0

**Comment by nathantsoi** [comment]
Maybe check: https://github.com/pjreddie/darknet/issues/485, seems to be an opencv issue?

here are my opencv flags:

```
> pkg-config --cflags opencv
-I/usr/local/include/opencv -I/usr/local/include
> pkg-config --libs --cflags opencv
-I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_cudabgsegm -lopencv_cudaobjdetect -lopencv_cudastereo -lopencv_dnn -lopencv_ml -lopencv_shape -lopencv_stitching -lopencv_cudafeatures2d -lopencv_superres -lopencv_cudacodec -lopencv_videostab -lopencv_cudaoptflow -lopencv_cudalegacy -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_photo -lopencv_imgcodecs -lopencv_cudawarping -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_video -lopencv_objdetect -lopencv_imgproc -lopencv_flann -lopencv_cudaarithm -lopencv_viz -lopencv_core -lopencv_cudev
```

also, I only use cuda 8, as in the original darknet

**Comment by yustiks** [comment]
I have the same issue when I compiled darknet 
"recipe for target 'obj/image_opencv.o' failed", I think the problem is connected with opencv version

**Comment by nathantsoi** [comment]
thx @yustiks!
