### ISSUE TITLE
question about box_c function

### ISSUE THREAD

**Issue by Windhelm-H** [generalized-iou/g-darknet#4]
Dear professor:
    I am a student doing research on object detection. I have read your paper recently and I am very interested in it. So I'm reading your code now. But this function confused me.
boxabs box_c(box a, box b) {
  boxabs ba = {0};
  ba.top = fmin(a.y - a.h/2, b.y - b.h/2);
  ba.bot = fmin(a.y + a.h/2, b.y + b.h/2);
  ba.left = fmin(a.x - a.w/2, b.x - b.w/2);
  ba.right = fmax(a.x + a.w/2, b.x + b.w/2);
  return ba;
    Should we use the fmin() but not the fmax() when we calculate ba.bot?
    I would appreciate it if you could spare time to reply to me.
}

**Comment by nathantsoi** [comment]
you're absolutely right, this is a typo, fixed in #a8266bb3
