### ISSUE TITLE
RPN network does not use giou?

### ISSUE THREAD

**Issue by oysz2016** [generalized-iou/g-darknet#6]
Thank you very much for being open about your work.In the code, only g-iou is used in fast RCNN, but not in RPN.
It seems that this point is not mentioned in the paper. Is the experiment designed according to the code?

**Comment by Smoothing97** [comment]
same question with you that where should we add GIOU loss in Faster RCNN.However,this code is GIOU-yolo,not faster rcnn.I change the iou calculate code in anchor target layer and proposal target layer in Faster RCNN which is really easy,finding how to add GIOU loss in Faster RCNN loss..

**Comment by Smoothing97** [comment]
@oysz2016

**Comment by oysz2016** [comment]
> same question with you that where should we add GIOU loss in Faster RCNN.However,this code is GIOU-yolo,not faster rcnn.I change the iou calculate code in anchor target layer and proposal target layer in Faster RCNN which is really easy,finding how to add GIOU loss in Faster RCNN loss..

@Smoothing97.sorry,I misread the catalogue，The "issue" should be written under "Detectron. Pytorch".In the "Detectron. Pytorch" RPN code, the original bounding box regression is used.

**Comment by zqdeepbluesky** [comment]
@Smoothing97  the same question ,how to add  giou loss in faster  rcnn?

**Comment by nathantsoi** [comment]
I think these comments are on the wrong repository. Did you perhaps mean to post here? https://github.com/generalized-iou/Detectron.pytorch/issues
