### ISSUE TITLE
delta_yolo_box

### ISSUE THREAD

**Issue by lz20061213** [generalized-iou/g-darknet#9]
Very nice work!
I have a small question about the delta_yolo_box function:
the pred box is calculated by 
`   b.x = (i + x[index + 0*stride]) / lw;
    b.y = (j + x[index + 1*stride]) / lh;
`
and we know 
`
b.l = b.x - b.w /2;
b.r = b.x + b.w/2;
`
but the delta is
`delta[index + 0*stride] = all_ious.dx_iou.dl + all_ious.dx_iou.dr`,
is there missing a scale of 1/ lw? or just using  iou_normalizer for all scale parameters?

**Comment by nathantsoi** [comment]
A couple thoughts:

`lw` and `lh` are applied to both the prediction and ground truth boxes before the gradient is calculated.

The giou loss is scale invariant (unlike MSE).

The iou/giou normalizer (e.g. `iou_normalizer`) is to regularize between the classification and localization losses during training.
